# Generated by Django 5.0.8 on 2024-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal_price',
            field=models.IntegerField(default=0),
        ),
    ]
